### ISSUE TITLE
Playback on other clients fails to start if Plex server listens on port 80 or 443

### ISSUE THREAD

**Issue by Lochnair** [samcm/synclounge#203] opened 2020-05-16 07:12 UTC
### Web App

**System Details**

- Operating System: Linux
- Web Browser name and version: Firefox 76.0.1

**Plex Media Server details**

- Version: 1.19.3.2764
- Operating System (Windows/Linux/Mac): Linux
- Running in Docker? (Yes/No): Yes
- Location (Local/Remote): Remote
- Remote Access Enabled (Yes/No)?: Yes, but through a reverse proxy

**Plex Client details**

- Name: Plex Android
- Version: 8.0.1.17410
- Network connection (Wired/Wifi): Wifi
- Platform: Android

### Issue information

**To Reproduce**

- Have a Plex server behind a reverse proxy listening on a standard port (80/443)
- Connect to a Plex client (I've attempted with Android and PMP)
- Join a room and attempt playback

**Describe your bug/issue**

Enabling network logging on the Plex Android app gets me this:
```
05-16 08:42:39.232  i: [PlexDevice] PMS Setting https://<domain>:0 token: true types: [discovered] state: Unknown as the new active connection.
05-16 08:42:39.233  i: [pms] /<desktopIP>:37128 - OPTIONS /player/timeline/poll
05-16 08:42:39.236  i: [pms] /<desktopIP>:37126 - OPTIONS /player/timeline/poll
05-16 08:42:39.240  i: [pms] /<desktopIP>:37130 - GET /player/timeline/poll
05-16 08:42:39.245  i: [pms] /<desktopIP>:37132 - GET /player/timeline/poll
05-16 08:42:39.286  i: Fetching [method:GET] https://<domain>:0/?X-Plex-Token=<token>&includeExternalMedia=1
05-16 08:42:39.294  i: [pms] /<desktopIP>:37134 - GET /player/timeline/poll
05-16 08:42:39.294  i: Fetching [method:GET] https://<domain>:0/library/metadata/1612?X-Plex-Token=<token>&includeExternalMedia=1
05-16 08:42:39.299  e: An exception occurred: java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 0
05-16 08:42:39.299  e: Stacktrace: java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 0
	at java.util.Vector.get(Vector.java:748)
	at com.plexapp.plex.f.p0$a.a(SourceFile:12)
	at com.plexapp.plex.f.p0$a.doInBackground(SourceFile:1)
	at android.os.AsyncTask$3.call(AsyncTask.java:378)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
```

I noticed that the port the client tries is 0, and that "port=" in the HTTP request. So I modified it and resent with the port set to 443, which starts playback.

Looking through the code I found this:
https://github.com/samcm/synclounge/blob/aa7c8992f08a572b92e69d56f131515b6f1a6349/src/store/modules/plex/helpers/PlexClient.js#L311

Which I believe is the cause of the issue (introduced in #196).

**Comment by xthursdayx** [comment] 2020-06-18 16:15
@Lochnair I think I'm having the same issue. How did you modify the port the clients try to connect to?

**Comment by ttshivers** [comment] 2020-06-19 02:51
The issue is likely with the chosenConnection of the server and it having a port of 0 if it the port is 0 in the query params

**Comment by xthursdayx** [comment] 2020-06-19 04:16
Right, I get it now. I usually allow external users to access my Plex server via a subdomain reverse proxy (at port 443), so hadn't set up a dedicated port for remote access in Plex, nor set up a port forward, so Synclounge was trying to connect to the server via port 0. Fixed now with a remote access port set and a port forward in place.

**Closed** 2020-08-26 00:03 UTC
Labels: no-issue-activity
