### ISSUE TITLE
Video issue

### ISSUE THREAD

**Issue by JeffIsTheCorn** [samcm/synclounge#83] opened 2018-07-23 23:04 UTC
![image](https://user-images.githubusercontent.com/30010449/43107449-115911a6-8eab-11e8-9dc5-7f748832c20b.png)

As show in the above image, the bottom of the video seems to just stretch out a row of pixels.  This is not an issue in other video players.  Not sure what's causing this.

**Comment by samcm** [comment] 2018-07-24 06:50
I'm honestly not sure what would be causing this - maybe its something to do with the aspect ratio? Does it occur on movies/16:9 TV Shows?

**Comment by JeffIsTheCorn** [comment] 2018-07-25 23:15
After checking other videos of the same and different aspect ratios I've discovered that it seems to just be an issue with this specific show.  Playing the show in a different video player or even in Plex doesn't cause this issue.  Perhaps it's a transcoding problem?  I'm not familiar enough with video to know if that would cause something like this.

**Comment by dgw** [comment] 2018-07-26 02:18
Could be a transcoding issue, could be something funky with the specific rip you have. My own DVD rip of that DS9 episode doesn't behave that way in the SyncLounge player. Maybe make sure SL is playing "Original" quality?

**Comment by dgw** [comment] 2018-07-26 03:10
Here's the video track info for my copy of this episode:

````mediainfo
Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4
Format settings                          : CABAC / 16 Ref Frames
Format settings, CABAC                   : Yes
Format settings, ReFrames                : 16 frames
Codec ID                                 : V_MPEG4/ISO/AVC
Bit rate                                 : 1 698 kb/s
Width                                    : 704 pixels
Height                                   : 480 pixels
Display aspect ratio                     : 4:3
Frame rate mode                          : Variable
Original frame rate                      : 24.080 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.209
Writing library                          : x264 core 77 r1292 e381f6d
Encoding settings                        : cabac=1 / ref=16 / deblock=1:-3:-3 / analyse=0x3:0x133 / me=tesa / subme=10 / psy=1 / psy_rd=1.0:0.1 / mixed_ref=1 / me_range=32 / chroma_me=1 / trellis=2 / 8x8dct=1 / cqm=0 / deadzone=21,11 / chroma_qp_offset=-3 / threads=6 / nr=0 / decimate=0 / mbaff=0 / constrained_intra=0 / bframes=8 / b_pyramid=1 / b_adapt=2 / b_bias=0 / direct=3 / wpredb=1 / keyint=250 / keyint_min=25 / scenecut=40 / rc=2pass / mbtree=0 / bitrate=1698 / ratetol=1.0 / qcomp=0.60 / qpmin=10 / qpmax=51 / qpstep=4 / cplxblur=20.0 / qblur=0.5 / ip_ratio=1.40 / pb_ratio=1.30 / aq=1:1.10
Language                                 : English
Default                                  : Yes
Forced                                   : No
````

**Comment by JeffIsTheCorn** [comment] 2018-07-26 23:02
These are the details for mine.  There are a few differences, but I'm not sure which are causing this issue.
```
Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L3.1
Format settings                          : CABAC / 9 Ref Frames
Format settings, CABAC                   : Yes
Format settings, RefFrames               : 9 frames
Codec ID                                 : V_MPEG4/ISO/AVC
Duration                                 : 45 min 30 s
Bit rate                                 : 1 240 kb/s
Width                                    : 720 pixels
Height                                   : 480 pixels
Display aspect ratio                     : 4:3
Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.150
Stream size                              : 393 MiB (71%)
Writing library                          : x264 core 104 r1677 19df41a
Encoding settings                        : cabac=1 / ref=9 / deblock=1:0:0 / analyse=0x3:0x133 / me=umh / subme=10 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=0 / me_range=64 / chroma_me=1 / trellis=2 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=0 / chroma_qp_offset=-2 / threads=12 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / constrained_intra=0 / bframes=9 / b_pyramid=2 / b_adapt=2 / b_bias=0 / direct=3 / weightb=1 / open_gop=0 / weightp=2 / keyint=240 / keyint_min=23 / scenecut=40 / intra_refresh=0 / rc_lookahead=40 / rc=2pass / mbtree=1 / bitrate=1240 / ratetol=1.0 / qcomp=0.60 / qpmin=10 / qpmax=51 / qpstep=4 / cplxblur=20.0 / qblur=0.5 / ip_ratio=1.40 / aq=1:1.00
Language                                 : English
Default                                  : Yes
Forced                                   : No
Color range                              : Limited
Color primaries                          : BT.601 NTSC
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.601
```

**Comment by samcm** [comment] 2018-07-27 08:41
Definitely could be a transcode issue - could you try disabling `Force Transcode` in SyncLounge Settings? The inbuilt player defaults to ON for compatibility. You should then hopefully get a Direct Stream out of PMS if you're still on Original quality.

**Comment by JeffIsTheCorn** [comment] 2018-07-27 22:41
Turning off force transcode seems to just crop the image.  Take a look at the two screenshots, the first from SyncLounge and the second from MPC-HC:

![image](https://user-images.githubusercontent.com/30010449/43349080-5de3d65a-91cb-11e8-8da2-e4e6661255b2.png)
![image](https://user-images.githubusercontent.com/30010449/43349084-631136ea-91cb-11e8-8598-3f38644033bd.png)

Streaming to other devices online through Plex doesn't have this issue, either.  Here is a screenshot of me streaming it on my phone over 4G:

![image](https://user-images.githubusercontent.com/30010449/43349252-93bc77ea-91cc-11e8-85d4-d54c3940ec6d.png)

I can test other things I may have missed if that helps.

**Comment by samcm** [comment] 2018-08-17 23:30
I'm gonna close this for now as I'm somewhat powerless in fixing it and it seems to be a pretty rare edge case. I suspect the issue is somewhere in either the transcoder or videojs. Either way it's unlikely I'll have the time in the future to investigate further. Sorry :(

**Closed by samcm** 2018-08-17 23:30 UTC
